### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: "*" # '*' stands for all self IPs
  drone1: 10.42.0.119
  drone2: 10.42.0.62
  drone3: 10.42.0.157
  friend: 10.42.0.205
  neighbor: 127.0.0.1 # modify to the IP of other machines

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
  - topic_name: /drone1/optitrack/pose # send the messages of this ROS topic
    msg_type: geometry_msgs/PoseStamped
    max_freq: 200
    srcIP: self
    srcPort: 3100
  - topic_name: /drone2/optitrack/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 200
    srcIP: self
    srcPort: 3200
  - topic_name: /drone3/optitrack/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 200
    srcIP: self
    srcPort: 3300
  - topic_name: /traj_start_trigger
    msg_type: geometry_msgs/PoseStamped
    max_freq: 1
    srcIP: self
    srcPort: 3001
  - topic_name: /pedestrian1/optitrack/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 50
    srcIP: self
    srcPort: 3011
  - topic_name: /pedestrian2/optitrack/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 50
    srcIP: self
    srcPort: 3012
  - topic_name: /pedestrian3/optitrack/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 50
    srcIP: self
    srcPort: 3013
  - topic_name: /px4ctrl/takeoff_land
    msg_type: quadrotor_msgs/TakeoffLand
    max_freq: 10
    srcIP: self
    srcPort: 3002

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
  - topic_name: /broadcast_particles
    msg_type: geometry_msgs/PolygonStamped
    srcPort: 3104
    srcIP: drone1

  - topic_name: /broadcast_particles
    msg_type: geometry_msgs/PolygonStamped
    srcPort: 3204
    srcIP: drone2

  - topic_name: /broadcast_particles
    msg_type: geometry_msgs/PolygonStamped
    srcPort: 3304
    srcIP: drone3

  - topic_name: /broadcast_traj
    msg_type: traj_utils/BezierTraj
    srcPort: 3105
    srcIP: drone1

  - topic_name: /broadcast_traj
    msg_type: traj_utils/BezierTraj
    srcPort: 3205
    srcIP: drone2

  - topic_name: /broadcast_traj
    msg_type: traj_utils/BezierTraj
    srcPort: 3305
    srcIP: drone3

  ## local_position/pose
  - topic_name: /drone1/mavros/local_position/pose
    msg_type: geometry_msgs/PoseStamped
    srcIP: drone1
    srcPort: 3101

  - topic_name: /drone2/mavros/local_position/pose
    msg_type: geometry_msgs/PoseStamped
    srcIP: drone2
    srcPort: 3201

  - topic_name: /drone3/mavros/local_position/pose
    msg_type: geometry_msgs/PoseStamped
    srcIP: drone3
    srcPort: 3301

  ## traj_server/desired_position
  - topic_name: /drone1/traj_server/desired_position
    msg_type: geometry_msgs/PoseStamped
    srcIP: drone1
    srcPort: 3122

  - topic_name: /drone2/traj_server/desired_position
    msg_type: geometry_msgs/PoseStamped
    srcIP: drone2
    srcPort: 3222

  - topic_name: /drone3/traj_server/desired_position
    msg_type: geometry_msgs/PoseStamped
    srcIP: drone3
    srcPort: 3322

  ## drone1 visualization
  - topic_name: /drone1/planner/map/occupancy_inflated
    msg_type: sensor_msgs/PointCloud2
    srcPort: 3111
    srcIP: drone1
  - topic_name: /drone1/planner/vis_mesh
    msg_type: visualization_msgs/Marker
    srcPort: 3112
    srcIP: drone1
  - topic_name: /drone1/planner/vis_astar_path
    msg_type: visualization_msgs/Marker
    srcPort: 3113
    srcIP: drone1
  - topic_name: /drone1/planner/vis_obstacle
    msg_type: sensor_msgs/PointCloud2
    srcPort: 3114
    srcIP: drone1
  - topic_name: /drone1/planner/trajectory
    msg_type: traj_utils/BezierTraj
    srcPort: 3115
    srcIP: drone1

  ## drone2 visualization
  - topic_name: /drone2/planner/map/occupancy_inflated
    msg_type: sensor_msgs/PointCloud2
    srcPort: 3211
    srcIP: drone2
  - topic_name: /drone2/planner/vis_mesh
    msg_type: visualization_msgs/Marker
    srcPort: 3212
    srcIP: drone2
  - topic_name: /drone2/planner/vis_astar_path
    msg_type: visualization_msgs/Marker
    srcPort: 3213
    srcIP: drone2
  - topic_name: /drone2/planner/vis_obstacle
    msg_type: sensor_msgs/PointCloud2
    srcPort: 3214
    srcIP: drone2
  - topic_name: /drone2/planner/trajectory
    msg_type: traj_utils/BezierTraj
    srcPort: 3215
    srcIP: drone2

  ## drone3 visualization
  - topic_name: /drone3/planner/map/occupancy_inflated
    msg_type: sensor_msgs/PointCloud2
    srcPort: 3311
    srcIP: drone3
  - topic_name: /drone3/planner/vis_mesh
    msg_type: visualization_msgs/Marker
    srcPort: 3312
    srcIP: drone3
  - topic_name: /drone3/planner/vis_astar_path
    msg_type: visualization_msgs/Marker
    srcPort: 3313
    srcIP: drone3
  - topic_name: /drone3/planner/vis_obstacle
    msg_type: sensor_msgs/PointCloud2
    srcPort: 3314
    srcIP: drone3
  - topic_name: /drone3/planner/trajectory
    msg_type: traj_utils/BezierTraj
    srcPort: 3315
    srcIP: drone3
