### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: "*" # '*' stands for all self IPs
  drone2: 10.42.0.62
  drone3: 10.42.0.157
  laptop: 10.42.0.1
  neighbor: 127.0.0.1 # modify to the IP of other machines

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
  #   - topic_name: /drone1/shared_trajectory
  #     msg_type: quadrotor_msgs/BezierCurve
  #     max_freq: 100
  #     srcIP: self
  #     srcPort: 3500
  - topic_name: /mavros/local_position/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 100
    srcIP: self
    srcPort: 3101
  - topic_name: /mavros/global_position/pose
    msg_type: geometry_msgs/PoseStamped
    srcIP: self
    srcPort: 3102
  - topic_name: /traj_server/desired_position
    msg_type: geometry_msgs/PoseStamped
    max_freq: 100
    srcIP: self
    srcPort: 3122


####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
  # - topic_name: chatter_recv_1 # the received messages will be published in this topic
  #   msg_type: std_msgs/String # ROS message type (rosmsg style)
  #   srcIP: drone1 # message source IPname
  #   srcPort: 3003 # message source port

  - topic_name: /traj_start_trigger
    msg_type: geometry_msgs/PoseStamped
    srcIP: laptop
    srcPort: 3011

  - topic_name: /mavros/vision_pose/pose # send the messages of this ROS topic
    msg_type: geometry_msgs/PoseStamped
    srcIP: laptop
    srcPort: 3100
