### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: "*" # '*' stands for all self IPs
  drone2: 10.42.0.62
  drone3: 10.42.0.157
  laptop: 10.42.0.1
  neighbor: 127.0.0.1 # modify to the IP of other machines

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
  - topic_name: /mavros/local_position/pose
    msg_type: geometry_msgs/PoseStamped
    max_freq: 100
    srcIP: self
    srcPort: 3101
  - topic_name: /mavros/global_position/pose
    msg_type: geometry_msgs/PoseStamped
    srcIP: self
    srcPort: 3102
  - topic_name: /broadcast_particles
    msg_type: geometry_msgs/PolygonStamped
    max_freq: 5
    srcPort: 3104
    srcIP: self
  - topic_name: /broadcast_traj
    msg_type: traj_utils/BezierTraj
    max_freq: 10
    srcPort: 3105
    srcIP: self
  - topic_name: /planner/map/occupancy_inflated
    msg_type: sensor_msgs/PointCloud2
    max_freq: 20
    srcPort: 3111
    srcIP: self
  - topic_name: /planner/vis_mesh
    msg_type: visualization_msgs/Marker
    max_freq: 20
    srcPort: 3112
    srcIP: self
  - topic_name: /planner/vis_astar_path
    msg_type: visualization_msgs/Marker
    max_freq: 20
    srcPort: 3113
    srcIP: self

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
  # - topic_name: chatter_recv_1 # the received messages will be published in this topic
  #   msg_type: std_msgs/String # ROS message type (rosmsg style)
  #   srcIP: drone1 # message source IPname
  #   srcPort: 3003 # message source port

  - topic_name: /traj_start_trigger
    msg_type: geometry_msgs/PoseStamped
    srcIP: laptop
    srcPort: 3011

  - topic_name: /mavros/vision_pose/pose # send the messages of this ROS topic
    msg_type: geometry_msgs/PoseStamped
    srcIP: laptop
    srcPort: 3100

  - topic_name: /broadcast_particles
    msg_type: geometry_msgs/PolygonStamped
    srcPort: 3204
    srcIP: drone2

  - topic_name: /broadcast_particles
    msg_type: geometry_msgs/PolygonStamped
    srcPort: 3304
    srcIP: drone3

  - topic_name: /broadcast_traj
    msg_type: traj_utils/BezierTraj
    srcPort: 3205
    srcIP: drone2

  - topic_name: /broadcast_traj
    msg_type: traj_utils/BezierTraj
    srcPort: 3305
    srcIP: drone3
