### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: "*" # '*' stands for all self IPs
  gcs: 192.168.101.138
  gcs2: 192.168.101.10
  drone1: 192.168.101.151
  drone2: 192.168.101.152
  drone3: 192.168.101.153
  drone4: 192.168.101.154
  drone5: 192.168.101.155

  drone6: 192.168.101.57
  drone7: 192.168.101.58
  drone8: 192.168.101.62
  drone9: 192.168.101.64
  drone10: 192.168.101.65
  neighbor: 127.0.0.1 # modify to the IP of other machines

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
## 30xx  drone -> ground station
## 31xx  drone -> drone
## 32xx  ground station -> drone
send_topics:
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: self
    max_freq: 10
    srcPort: 3001

  - topic_name: odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: self
    max_freq: 20
    srcPort: 3002
  
  - topic_name: ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: self
    max_freq: 20
    srcPort: 3003

  - topic_name: ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: self
    max_freq: 20
    srcPort: 3004

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
  - topic_name: /broadcast_traj_to_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: gcs
    srcPort: 3200

  - topic_name: /joystick_from_bridge
    msg_type: sensor_msgs/Joy
    srcIP: gcs
    srcPort: 3201

  - topic_name: odometry
    msg_type: nav_msgs/Odometry
    srcIP: gcs
    srcPort: 3210

