### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: "*" # '*' stands for all self IPs
  gcs: 192.168.101.138
  gcs2: 192.168.101.10
  drone1: 192.168.101.151
  drone2: 192.168.101.152
  drone3: 192.168.101.153
  drone4: 192.168.101.154
  drone5: 192.168.101.155
  drone6: 192.168.101.157
  drone7: 192.168.101.158
  neighbor: 127.0.0.1 # modify to the IP of other machines

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
## 30xx  drone -> ground station
## 31xx  drone -> drone
## 32xx  ground station -> drone
send_topics:
  - topic_name: /move_base_simple/goal # start trigger
    msg_type: geometry_msgs/PoseStamped
    srcIP: self
    srcPort: 3200
    max_freq: 5
  - topic_name: /px4ctrl/takeoff_land
    msg_type: quadrotor_msgs/TakeoffLand
    srcIP: self
    srcPort: 3201
    max_freq: 5
  - topic_name: /multi_map_manager/chunk_stamps_send
    msg_type: plan_env/ChunkStamps
    max_freq: 20
    srcIP: self
    srcPort: 3100
  - topic_name: /multi_map_manager/chunk_data_send
    msg_type: plan_env/ChunkData
    max_freq: 20
    srcIP: self
    srcPort: 3101

# TODO: send takeoff and land topic

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
  - topic_name: /quad_1/global/odom
    msg_type: nav_msgs/Odometry
    srcIP: drone1
    srcPort: 3001
  - topic_name: /quad_2/global/odom
    msg_type: nav_msgs/Odometry
    srcIP: drone2
    srcPort: 3001
  - topic_name: /quad_3/global/odom
    msg_type: nav_msgs/Odometry
    srcIP: drone3
    srcPort: 3001
  - topic_name: /quad_4/global/odom
    msg_type: nav_msgs/Odometry
    srcIP: drone4
    srcPort: 3001
  - topic_name: /quad_5/global/odom
    msg_type: nav_msgs/Odometry
    srcIP: drone5
    srcPort: 3001
  - topic_name: /quad_6/global/odom
    msg_type: nav_msgs/Odometry
    srcIP: drone6
    srcPort: 3001
  - topic_name: /quad_7/global/odom
    msg_type: nav_msgs/Odometry
    srcIP: drone7
    srcPort: 3001

  # Visualization
  - topic_name: /quad_1/planning_vis/frontier
    msg_type: visualization_msgs/Marker
    srcIP: drone1
    srcPort: 3002
  - topic_name: /quad_2/planning_vis/frontier
    msg_type: visualization_msgs/Marker
    srcIP: drone2
    srcPort: 3002
  - topic_name: /quad_3/planning_vis/frontier
    msg_type: visualization_msgs/Marker
    srcIP: drone3
    srcPort: 3002
  - topic_name: /quad_4/planning_vis/frontier
    msg_type: visualization_msgs/Marker
    srcIP: drone4
    srcPort: 3002
  - topic_name: /quad_5/planning_vis/frontier
    msg_type: visualization_msgs/Marker
    srcIP: drone5
    srcPort: 3002
  - topic_name: /quad_6/planning_vis/frontier
    msg_type: visualization_msgs/Marker
    srcIP: drone6
    srcPort: 3002
  - topic_name: /quad_7/planning_vis/frontier
    msg_type: visualization_msgs/Marker
    srcIP: drone7
    srcPort: 3002

  - topic_name: /quad_1/planning_vis/trajectory
    msg_type: visualization_msgs/Marker
    srcIP: drone1
    srcPort: 3003
  - topic_name: /quad_2/planning_vis/trajectory
    msg_type: visualization_msgs/Marker
    srcIP: drone2
    srcPort: 3003
  - topic_name: /quad_3/planning_vis/trajectory
    msg_type: visualization_msgs/Marker
    srcIP: drone3
    srcPort: 3003
  - topic_name: /quad_4/planning_vis/trajectory
    msg_type: visualization_msgs/Marker
    srcIP: drone4
    srcPort: 3003
  - topic_name: /quad_5/planning_vis/trajectory
    msg_type: visualization_msgs/Marker
    srcIP: drone5
    srcPort: 3003
  - topic_name: /quad_6/planning_vis/trajectory
    msg_type: visualization_msgs/Marker
    srcIP: drone6
    srcPort: 3003
  - topic_name: /quad_7/planning_vis/trajectory
    msg_type: visualization_msgs/Marker
    srcIP: drone7
    srcPort: 3003

  - topic_name: /multi_map_manager/chunk_stamps_recv
    msg_type: plan_env/ChunkStamps
    srcIP: drone1
    srcPort: 3100
  - topic_name: /multi_map_manager/chunk_stamps_recv
    msg_type: plan_env/ChunkStamps
    srcIP: drone2
    srcPort: 3100
  - topic_name: /multi_map_manager/chunk_stamps_recv
    msg_type: plan_env/ChunkStamps
    srcIP: drone3
    srcPort: 3100
  - topic_name: /multi_map_manager/chunk_stamps_recv
    msg_type: plan_env/ChunkStamps
    srcIP: drone4
    srcPort: 3100
  - topic_name: /multi_map_manager/chunk_stamps_recv
    msg_type: plan_env/ChunkStamps
    srcIP: drone5
    srcPort: 3100
  - topic_name: /multi_map_manager/chunk_stamps_recv
    msg_type: plan_env/ChunkStamps
    srcIP: drone6
    srcPort: 3100
  - topic_name: /multi_map_manager/chunk_stamps_recv
    msg_type: plan_env/ChunkStamps
    srcIP: drone7
    srcPort: 3100

  - topic_name: /multi_map_manager/chunk_data_recv
    msg_type: plan_env/ChunkData
    srcIP: drone1
    srcPort: 3101
  - topic_name: /multi_map_manager/chunk_data_recv
    msg_type: plan_env/ChunkData
    srcIP: drone2
    srcPort: 3101
  - topic_name: /multi_map_manager/chunk_data_recv
    msg_type: plan_env/ChunkData
    srcIP: drone3
    srcPort: 3101
  - topic_name: /multi_map_manager/chunk_data_recv
    msg_type: plan_env/ChunkData
    srcIP: drone4
    srcPort: 3101
  - topic_name: /multi_map_manager/chunk_data_recv
    msg_type: plan_env/ChunkData
    srcIP: drone5
    srcPort: 3101
  - topic_name: /multi_map_manager/chunk_data_recv
    msg_type: plan_env/ChunkData
    srcIP: drone6
    srcPort: 3101
  - topic_name: /multi_map_manager/chunk_data_recv
    msg_type: plan_env/ChunkData
    srcIP: drone7
    srcPort: 3101

  - topic_name: /swarm_expl/drone_state
    msg_type: exploration_manager/DroneState
    srcIP: drone1
    srcPort: 3102
  - topic_name: /swarm_expl/drone_state
    msg_type: exploration_manager/DroneState
    srcIP: drone2
    srcPort: 3102
  - topic_name: /swarm_expl/drone_state
    msg_type: exploration_manager/DroneState
    srcIP: drone3
    srcPort: 3102
  - topic_name: /swarm_expl/drone_state
    msg_type: exploration_manager/DroneState
    srcIP: drone4
    srcPort: 3102
  - topic_name: /swarm_expl/drone_state
    msg_type: exploration_manager/DroneState
    srcIP: drone5
    srcPort: 3102
  - topic_name: /swarm_expl/drone_state
    msg_type: exploration_manager/DroneState
    srcIP: drone6
    srcPort: 3102
  - topic_name: /swarm_expl/drone_state
    msg_type: exploration_manager/DroneState
    srcIP: drone7
    srcPort: 3102

  - topic_name: /quad_1/planning/swarm_traj
    msg_type: bspline/Bspline
    srcIP: drone1
    srcPort: 3105
  - topic_name: /quad_2/planning/swarm_traj
    msg_type: bspline/Bspline
    srcIP: drone2
    srcPort: 3105
  - topic_name: /quad_3/planning/swarm_traj
    msg_type: bspline/Bspline
    srcIP: drone3
    srcPort: 3105
  - topic_name: /quad_4/planning/swarm_traj
    msg_type: bspline/Bspline
    srcIP: drone4
    srcPort: 3105
  - topic_name: /quad_5/planning/swarm_traj
    msg_type: bspline/Bspline
    srcIP: drone5
    srcPort: 3105
  - topic_name: /quad_6/planning/swarm_traj
    msg_type: bspline/Bspline
    srcIP: drone6
    srcPort: 3105
  - topic_name: /quad_7/planning/swarm_traj
    msg_type: bspline/Bspline
    srcIP: drone7
    srcPort: 3105

  - topic_name: /quad_6/sdf_map/occupancy_all
    msg_type: sensor_msgs/PointCloud2
    srcIP: drone6
    srcPort: 3004
  - topic_name: /quad_7/sdf_map/occupancy_all
    msg_type: sensor_msgs/PointCloud2
    srcIP: drone7
    srcPort: 3004

  - topic_name: /quad_1/planning/viewpoints
    msg_type: visualization_msgs/Marker
    srcIP: drone1
    srcPort: 3006
  - topic_name: /quad_2/planning/viewpoints
    msg_type: visualization_msgs/Marker
    srcIP: drone2
    srcPort: 3006
  - topic_name: /quad_3/planning/viewpoints
    msg_type: visualization_msgs/Marker
    srcIP: drone3
    srcPort: 3006
  - topic_name: /quad_4/planning/viewpoints
    msg_type: visualization_msgs/Marker
    srcIP: drone4
    srcPort: 3006
  - topic_name: /quad_5/planning/viewpoints
    msg_type: visualization_msgs/Marker
    srcIP: drone5
    srcPort: 3006
  - topic_name: /quad_6/planning/viewpoints
    msg_type: visualization_msgs/Marker
    srcIP: drone6
    srcPort: 3006
  - topic_name: /quad_7/planning/viewpoints
    msg_type: visualization_msgs/Marker
    srcIP: drone7
    srcPort: 3006
